libarchive: add -latomic to libs to avoid linker problems. undefined reference to `__atomic_ trying to perform 64-bit atomic operations and 32-bit ARM hardware doesn't have native instructions to handle 64-bit atomics